"""empty message

Revision ID: 11334768a438
Revises: 5f34712b25c7
Create Date: 2022-01-05 21:29:10.086414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11334768a438'
down_revision = '5f34712b25c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'seeking_venue')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_venue', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
