"""empty message

Revision ID: f4d83e0605f5
Revises: 05a4ebad2453
Create Date: 2022-01-06 21:59:43.644082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4d83e0605f5'
down_revision = '05a4ebad2453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('website_link', sa.String(length=100), nullable=True))
    op.add_column('venue', sa.Column('seeking_description', sa.String(length=100), nullable=True))
    op.drop_column('venue', 'website')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('website', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('venue', 'seeking_description')
    op.drop_column('venue', 'website_link')
    # ### end Alembic commands ###
