"""empty message

Revision ID: 79795cd0fe1b
Revises: d94a1dc49595
Create Date: 2022-01-05 20:52:24.392658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79795cd0fe1b'
down_revision = 'd94a1dc49595'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'seeking_venue',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'seeking_venue',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
